import type { WebsiteData } from "@/types/website-data"

/**
 * Generates HTML for a PDF report
 */
export function generatePdfHtml(data: WebsiteData, includeScreenshot = true): string {
  const screenshotHtml =
    includeScreenshot && data.screenshotUrl
      ? `<div style="margin: 20px 0;">
        <img src="${data.screenshotUrl}" alt="Screenshot of ${data.title}" style="max-width: 100%; border: 1px solid #ddd; border-radius: 4px;" />
      </div>`
      : ""

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Website Analysis: ${data.title}</title>
  <style>
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1, h2, h3 {
      color: #444;
    }
    h1 {
      border-bottom: 2px solid #8b5cf6;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }
    h2 {
      border-bottom: 1px solid #ddd;
      padding-bottom: 5px;
      margin-top: 30px;
    }
    .url {
      color: #666;
      font-style: italic;
      margin-bottom: 20px;
    }
    .summary {
      background-color: #f9f9f9;
      padding: 15px;
      border-left: 4px solid #8b5cf6;
      margin-bottom: 20px;
    }
    .key-points li {
      margin-bottom: 10px;
    }
    .keywords {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      margin-bottom: 20px;
    }
    .keyword {
      background-color: #f0f0f0;
      padding: 5px 10px;
      border-radius: 15px;
      font-size: 0.9em;
    }
    .score-container {
      display: flex;
      justify-content: space-between;
      margin-bottom: 20px;
    }
    .score-box {
      text-align: center;
      padding: 15px;
      background-color: #f5f5f5;
      border-radius: 5px;
      width: 23%;
    }
    .score {
      font-size: 24px;
      font-weight: bold;
      color: #8b5cf6;
    }
    .improvements li {
      margin-bottom: 8px;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
      margin-bottom: 20px;
    }
    .stat-box {
      background-color: #f5f5f5;
      padding: 15px;
      border-radius: 5px;
      text-align: center;
    }
    .stat-value {
      font-size: 20px;
      font-weight: bold;
      color: #14b8a6;
    }
    .footer {
      margin-top: 40px;
      text-align: center;
      font-size: 0.9em;
      color: #666;
      border-top: 1px solid #ddd;
      padding-top: 20px;
    }
  </style>
</head>
<body>
  <h1>Website Analysis Report</h1>
  <div class="url">${data.url}</div>
  
  <h2>Overview</h2>
  <div class="summary">${data.summary}</div>
  
  ${screenshotHtml}
  
  <h2>Key Points</h2>
  <ul class="key-points">
    ${data.keyPoints.map((point) => `<li>${point}</li>`).join("")}
  </ul>
  
  <h2>Keywords</h2>
  <div class="keywords">
    ${data.keywords.map((keyword) => `<span class="keyword">${keyword}</span>`).join("")}
  </div>
  
  <h2>Sustainability Metrics</h2>
  <div class="score-container">
    <div class="score-box">
      <div class="score">${data.sustainability.score}%</div>
      <div>Overall Score</div>
    </div>
    <div class="score-box">
      <div class="score">${data.sustainability.performance}%</div>
      <div>Performance</div>
    </div>
    <div class="score-box">
      <div class="score">${data.sustainability.scriptOptimization}%</div>
      <div>Script Optimization</div>
    </div>
    <div class="score-box">
      <div class="score">${data.sustainability.duplicateContent}%</div>
      <div>Content Quality</div>
    </div>
  </div>
  
  <h2>Improvement Suggestions</h2>
  <ul class="improvements">
    ${data.sustainability.improvements.map((imp) => `<li>${imp}</li>`).join("")}
  </ul>
  
  <h2>Content Statistics</h2>
  <div class="stats-grid">
    <div class="stat-box">
      <div class="stat-value">${data.contentStats.wordCount}</div>
      <div>Words</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${data.contentStats.paragraphs}</div>
      <div>Paragraphs</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${data.contentStats.headings}</div>
      <div>Headings</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${data.contentStats.images}</div>
      <div>Images</div>
    </div>
    <div class="stat-box">
      <div class="stat-value">${data.contentStats.links}</div>
      <div>Links</div>
    </div>
  </div>
  
  <div class="footer">
    Generated by WebInsight on ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`
}
